name: datadog
version: '0.2.3.0'
author: Ian Duncan
maintainer: Ian Duncan <ian@iankduncan.com>, Kostiantyn Rybnikov <k-bx@k-bx.com>
license: MIT
license-file: LICENSE
synopsis: 'Datadog client for Haskell. Supports both the HTTP API and StatsD.'
homepage: 'https://github.com/iand675/datadog'
category: Network
build-type: Simple

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  # - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PackageImports
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  # - -Werror
  - -fwarn-tabs
  - -O2

dependencies:
  - aeson
  - atomic-primops
  - auto-update
  - base >= 4.7 && < 5
  - buffer-builder
  - bytestring
  - containers
  - clock
  - conduit
  - conduit-extra
  - dlist
  - exceptions
  - http-client
  - http-client-tls
  - http-types
  - lens
  - resourcet
  - mtl
  - mwc-random
  - network
  - old-locale
  - text
  - time
  - transformers-base
  - unliftio
  - unordered-containers
  - unliftio
  - vector

library:
  source-dirs: src

tests:
  datadog-api-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - base
      - Cabal
      - exceptions
      - hspec
      - network
      - lens
      - random
      - text
      - time
      - datadog
